# Deployment configuration for Helm-nginx application
replicas: 2

appName: webapp

image:
  name: mholka1/webapp
  tag: latest

# Service configuration for Helm-nginx application
configmap:
  data:
    CUSTOM_HEADER: 'Hello World!'