apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.appName}}
  name: {{ .Values.appName}}
spec:
  replicas: {{ .Values.Replicas}}))
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
      - image: {{ .Values.Image}}:latest
        name: {{ .Values.appName}}
        resources: {}
status: {}
