apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: "{{ .Values.appName }}-service"
  selector:
    app: {{ .Values.appName }}
    
  type: NodePort